[theme]
primaryColor = "#4A6670"
backgroundColor = "#F6F4EF"
secondaryBackgroundColor = "#EDE9DF"
textColor = "#1B1E1C"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true


